FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages/db ./packages/db
COPY ./packages/typescript-config ./packages/typescript-config

COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/api ./apps/api

RUN pnpm install
RUN pnpm run db:generate

EXPOSE 8080

CMD ["pnpm", "run", "start:backend"]