services:
  postgres:
    container_name: postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=trial
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user_app:
    container_name: prisma-express-app
    build:
      context: ../ # Go up one directory to project root becsuse Dockerfile is in root
      dockerfile: docker/Dockerfile # Specify path to Dockerfile
    environment:
      - DATABASE_URL=postgresql://prisma:mysecretpassword@postgres:5432/trial
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres-data:
